#!/bin/bash


DCPPATH=$1
LOGFILE=$(find $1 -name "CPL*.xml" -exec basename {} \; | cut -f 1 -d '.')_$(date +"%Y%m%d_%H%M").log
LOGPATH="/mnt/BRAVO/di/zz_logs/dcp_inspect_logs"


# Verify if a path is provided as an argument
if $1
then
	echo "Please provide a complete DCP path"	
	exit 1
fi


if ls $1/ | grep "CPL"; then
	docker container run --rm -it -v $DCPPATH:/dcp -v $LOGPATH:/log jeajar/dcdt dcp_inspect -l /log/$LOGFILE /dcp/
else
	echo "Please provide a valid DCP path"
fi
